site_name: petropandas
repo_url: https://github.com/ondrolexa/petropandas
site_description: Pandas accessors for petrologists
site_author: Ondrej Lexa
edit_uri: edit/main/docs/
repo_name: ondrolexa/petropandas
copyright: Maintained by Ondrej Lexa.

nav:
  - Home: index.md
  - Tutorial: notebooks/tutorial.ipynb
  - Utilities: utils.md
  - Accessor: accessors.md
  - Plotting: plots.md
  - Minerals: minerals.md

plugins:
  - search
  - mkdocs-jupyter:
      execute: true
      allow_errors: false
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google
            show_bases: false
            inherited_members: true
            members_order: source
            group_by_category: true

theme:
  name: material
  features:
    - search.suggest
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.prune
    - toc.integrate
  font:
    text: Noto Sans Adlam Unjoined
    code: Roboto Mono
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: deep orange
      toggle:
        icon: material/weather-sunny
        name: Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: deep orange
      toggle:
        icon: material/weather-night
        name: Light mode
  icon:
    logo: fontawesome/solid/table
    repo: fontawesome/brands/github

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
