site_name: petropandas
repo_url: https://github.com/ondrolexa/petropandas
site_url: https://ondrolexa.github.io/petropandas
site_description: Pandas accessors for petrologists
site_author: Ondrej Lexa
edit_uri: edit/main/docs/
repo_name: ondrolexa/petropandas
copyright: Maintained by Ondrej Lexa.

nav:
  - Home: index.md
  - Accessors: accessors.md
  - Minerals: minerals.md
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          setup_commands:
            - import sys
            - sys.path.append('../')
          options:
            docstring_style: google
theme:
  name: material
  feature:
    tabs: true
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/ondrolexa/petropandas
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/petropandas

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
