[project]
name = "petropandas"
dynamic = ["version"]
description = "Pandas accessors for petrologists"
readme = "README.md"
maintainers = [{ name = "Ondrej Lexa", email = "lexa.ondrej@gmail.com" }]
requires-python = ">=3.10"
license = "MIT"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
    "License :: OSI Approved :: MIT License",
]
dependencies = [
    "numpy",
    "matplotlib",
    "pandas",
    "seaborn",
    "pyparsing",
    "xlrd",
    "openpyxl",
    "periodictable",
    "mpltern",
    "requests",
]

[project.optional-dependencies]
extra = ["jupyterlab"]
tests = ["pytest", "nbval"]
docs = ["mkdocs", "mkdocs-material", "mkdocstrings[python]", "mkdocs-jupyter"]
dev = ["petropandas[extra,tests,docs]", "black"]

[project.urls]
Homepage = "https://github.com/ondrolexa/petropandas"
Documentation = "https://petropandas.readthedocs.io"
Repository = "https://github.com/ondrolexa/petropandas.git"
Issues = "https://github.com/ondrolexa/petropandas/issues"

[tool.hatch.version]
path = "petropandas/__init__.py"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.black]
line-length = 88

[tool.isort]
profile = "black"

[tool.pytest.ini_options]
testpaths = ["tests", "docs/notebooks"]
